### ISSUE TITLE
How to render other datasets?

### ISSUE THREAD

**Issue by CoderT-ui** [Ervadar/svo-renderer#2]
Having a problem trying to change the rendered dataset from the inukshuk to the bunny. Only get a black screen even though console information says bunny.

**Comment by mmalesadev** [comment]
Thanks for pointing this out. As you can see, the project is still in development - I'm going to look into this issue right after I finish some other stuff (probably within one month).
Tbh, this project is very primitive in its current stage, so if you are looking for any inspiration/information I suggest other sources :) Closing this for now. Thanks again.
