### ISSUE TITLE
[Question] Hello

### ISSUE THREAD

**Issue by trsh** [Ervadar/svo-renderer#5]
Can u provide more info on what your build on? :)

**Comment by mmalesadev** [comment]
Hi. What exactly do you mean by that?
The project is currently in development, it may contain bugs and is not intended for external use :)

When I finish it (soon), I'm gonna change the description to something more descriptive ;)
For now I can tell you it was built on Windows 10 using CMake (if that was your question).

**Comment by trsh** [comment]
Just wanted to know more about the project and what it can do
